version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: mongo_db
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MYAPP_DB_USERNAME=${MYAPP_DB_USERNAME}
      - MYAPP_DB_PASSWORD=${MYAPP_DB_PASSWORD}
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./my-data/db:/data/db # Volume for MongoDB data
      - ./database/archive:/database/archive # Additional volume
    restart: always
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express:0.54
    ports:
      - '8081:8081'
    container_name: mongo_express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
    depends_on:
      - mongodb
    restart: always
    networks:
      - mongo-network
networks:
    mongo-network:
      driver: bridge