version: "3.9"

services:
  sqlite:
    image: alpine:3.14
    container_name: sqlite
    volumes:
      - ./data:/data
    command: ["sh", "-c", "apk add --no-cache sqlite3 && tail -f /dev/null"]

  sqlite-web:
    image: coleifer/sqlite-web:latest
    container_name: sqlite-web
    depends_on:
      - sqlite
    environment:
      - SQLITE_DATABASE=/data/db.sqlite
    volumes:
      - ./data:/data
    ports:
      - "8080:8080"
