#--------------------------------------------------------------------------
# ! The Docker Compose file is configured for local environments.
# ! Do not deploy this Docker Compose file in production environments.
#--------------------------------------------------------------------------

# Docker compose version https://docs.docker.com/compose/compose-file
version: "3.9"

# The Docker services.
services:
  # The MariaDB database container.
  mariadb:
    # https://hub.docker.com/_/mariadb
    image: mariadb:10.6
    container_name: "${DB_CONTAINER_NAME:-mariadb}"
    environment:
      MARIADB_ROOT_HOST: "%"
      MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${DB_DATABASE}"
      MARIADB_USER: "${DB_USERNAME}"
      MARIADB_PASSWORD: "${DB_PASSWORD}"
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_ROOT_PASSWORD}"]
      retries: 3
      timeout: 5s
    networks:
      - local
    # Map the database container exposed port to the host port.
    ports:
     - ${DB_PORT:-3306}:3306
    volumes:
      - mariadb_data:/var/lib/mysql



  # The phpMyAdmin service.
  phpmyadmin:
    # https://hub.docker.com/r/phpmyadmin/phpmyadmin
    image: phpmyadmin:5.1
    container_name: "${PMA_CONTAINER_NAME:-phpmyadmin}"
    environment:
      PMA_HOST: mariadb
      PMA_USER: "${DB_USERNAME}"
      PMA_PASSWORD: "${DB_PASSWORD}"
    depends_on:
      - mariadb
    networks:
      - local
    ports:
     - ${PMA_PORT:-8080}:80
# The Docker networks.
networks:
  local:
    driver: "bridge"
    name: ${NETWORK_NAME:-local_dbs_network}

# The Docker volumes.
volumes:
  mariadb_data:
    driver: "local"
    name: "${DB_VOLUME_NAME:-mariadb_data}"
