version: "3.9"
services:
    mysql:
      image: mysql:8.3
      container_name: mysql_db
      ports:
        - 3306:3306 
      environment:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_USER: ${MYSQL_USER} 
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      volumes:
        - ./mysql-data:/var/lib/mysql
        - /home/shashi/docker-databases/mysql/initdb/init.sql:/docker-entrypoint-initdb.d/init.sql:rw

      restart: always
    phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      ports:
        - 8080:80
      container_name: my_phpmyadmin
      restart: always
      environment:
        PMA_HOST: mysql
        PMA_PORTS: 3306
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      depends_on:
        - mysql
volumes: 
    mysql-data:
